[모휘정] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/29-westagram-backend-3-team pull request #11
Opened 2022-01-17 07:09 UTC by walkersmind

## 수정 사항 간략한 한줄 요약
- 로그인 기능 구현

## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-17 08:21 UTC, kangil2 commented
로그인 기능을 따로 분리를 시켜서 보기 편하게 만드셨네요 👍 👍

2022-01-17 08:25 UTC, kangil2 commented on students/hwijeong/westagram/login/views.py
> +            return JsonResponse({'message': "INVALID_USER"}, status=401)
```raise ValidationError({'message': "Please check email or password"})``` 조건문에서 발생시킨 에러 메세지를```
except ValidationError as e:```로 받은 다음 에러 메세지를 처리하시면 더 효율적일 것 같습니다!

2022-01-17 08:47 UTC, DongKey777 approved these changes
기능별로 앱을 분리하여 구조를 파악하기가 쉬웠습니다 ! :)

2022-01-17 08:48 UTC, DongKey777 reviewed
기능별로 앱을 분리하여 구조를 파악하기가 쉬웠습니다 ! :)

2022-01-18 01:33 UTC, lordmyshepherd requested changes

2022-01-18 01:33 UTC, lordmyshepherd commented on students/hwijeong/westagram/login/views.py
> +                raise ValidationError("INVALID_USER")
함수나 변수명은 snake_case를 사용해서 구현해주세요~

2022-01-18 01:58 UTC, walkersmind commented on students/hwijeong/westagram/login/views.py
> +                raise ValidationError("INVALID_USER")
넵 저번에도 지적해주신 부분인데 이름을 지을 때 한번 더 신중하게 확인하겠습니다.

2022-01-18 03:02 UTC, bigfanoftim approved these changes
휘정님 보통 로그인과 회원가입 로직같은 경우 앱을 분리하지 않고 하나의 `users`앱에 추가합니다. 하지만 개발엔 전혀 문제가 없기 때문에 merge하겠습니다! 다음번에 참고해서 진행해주세요!

2022-01-18 03:03 UTC, merged