[이동훈] 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/29-westagram-backend-3-team pull request #16
Opened 2022-01-18 06:32 UTC by DongKey777

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
-  회원가입 비밀번호 암호화 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-18 07:25 UTC, kangil2 commented
잘 쓰셨네요 굿굿 👍 👍

2022-01-18 07:40 UTC, walkersmind commented
질 봤습니다!  👍 👍 따로 수정 사항은 없어 보입니다!

2022-01-18 08:32 UTC, bigfanoftim requested changes

2022-01-18 08:32 UTC, bigfanoftim commented on students/donghun/users/views.py
>              return JsonResponse({"message":"KEY_ERROR"}, status=400)
```suggestion
            return JsonResponse({"message" : "success"}, status=201)
        except KeyError:
            return JsonResponse({"message" : "KEY_ERROR"}, status=400)
```

2022-01-18 08:32 UTC, bigfanoftim commented on students/donghun/users/views.py
> +
```suggestion
```

2022-01-18 08:32 UTC, bigfanoftim commented on students/donghun/users/views.py
> +            password = password_bcrypt
```suggestion
            password = user_data['password']
```

2022-01-18 08:32 UTC, bigfanoftim commented on students/donghun/users/views.py
>              REGEX_PHONE_NUMBER = '\d{3}-\d{3,4}-\d{4}'
```suggestion
            REGEX_EMAIL        = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
            REGEX_PASSWORD     = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&.]{8,}$'
            REGEX_PHONE_NUMBER = '\d{3}-\d{3,4}-\d{4}'
```

2022-01-18 08:32 UTC, bigfanoftim commented on students/donghun/users/views.py
>              User.objects.create(
`bcrypt.hashpw`의 경우 어차피 정규표현식을 통과해야만 활용되는 코드이기 때문에 정규표현식 검증을 다 통과하고 난 뒤 hash 된 비밀번호를 넣어서 create 하는 것이 더 효율적으로 보입니다.
```suggestion
            hashed_password = bcrypt.hashpw(...).decode('utf-8')
            User.objects.create(
                ...
                password = hashed_password
            )
```

2022-01-19 03:31 UTC, DongKey777 commented
피드백 주신 사항들 확인 후 수정했습니다 !

2022-01-19 07:24 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-01-19 07:24 UTC, merged