[모휘정] Mission 6: 로그인 JWT 발급
wecode-bootcamp-korea/29-westagram-backend-3-team pull request #17
Opened 2022-01-18 07:48 UTC by walkersmind

## 수정 사항 간략한 한줄 요약
- 로그인 JWT 발급 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일과 비밀번호 유효성 검사 후 JWT 발행
- 성공 시 토큰과 함께 메시지를 리턴

## 기타 질문 및 특이 사항
- 이메일을 통해 토큰을 발행했는데요, 괜찮은 것일까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-19 08:37 UTC, DongKey777 commented on students/hwijeong/westagram/login/views.py
> +                    payload = jwt.decode(access_token, SECRET_KEY, algorithms='HS256')
알고리즘도 my_setting 파일에 관리해주시면 좋을 것 같아요 !

2022-01-19 08:54 UTC, walkersmind commented on students/hwijeong/westagram/login/views.py
> +                    payload = jwt.decode(access_token, SECRET_KEY, algorithms='HS256')
그렇네요! 감사합니다!

2022-01-19 09:42 UTC, kangil2 commented on students/hwijeong/westagram/login/views.py
> +                    payload = jwt.decode(access_token, SECRET_KEY, algorithms='HS256')
제가 보기엔 완벽합니다... 👍 배워갑니다

2022-01-20 00:51 UTC, lordmyshepherd requested changes

2022-01-20 00:51 UTC, lordmyshepherd commented on students/hwijeong/westagram/login/views.py
> +                return payload
decoding하는 로직은 필요 없을 것 같습니다. 사용자 정보를 같이 반환해주려고 하는 목적이라면 line 22에 있는 user를 사용하시면 됩니다. 👍🏻

2022-01-20 00:51 UTC, lordmyshepherd commented on students/hwijeong/westagram/login/views.py
> +                return payload
```suggestion
```

2022-01-20 04:34 UTC, bigfanoftim requested changes

2022-01-20 04:34 UTC, bigfanoftim commented on students/hwijeong/westagram/login/views.py
> +                raise ValidationError("INVALID_PASSWORD")
불필요한 변수 지정인 것 같습니다!
```suggestion
            if not bcrypt.checkpw(password.encode('utf-8'), validated_user.password.encode('utf-8')):
                raise ValidationError("INVALID_PASSWORD")
```

2022-01-20 04:34 UTC, bigfanoftim commented on students/hwijeong/westagram/login/views.py
> +            user_information = decoding_access_token(access_token, SECRET_KEY)
`user_information`을 토큰에서 꺼낸다는건 `user_id`를 리턴해주고 싶다는 것으로 보여지네요.
- 그럼 우선 `user_id`를 굳이 토큰에서 꺼내올 필요가 없이 22번째  줄에서 `validated_user.id`로 사용할 수 있겠죠?
- 추가로 왜 프론트한테 `user_information`을 리턴해줘야 하는지가 궁금하네요. 불필요한 작업이 아닐까 생각됩니다.
```suggestion
```

2022-02-08 01:52 UTC, closed without merging