[이동훈] Mission : 6 로그인 JWT 발급
wecode-bootcamp-korea/29-westagram-backend-3-team pull request #20
Opened 2022-01-19 08:34 UTC by DongKey777

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 JWT 발급
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-19 08:58 UTC, walkersmind commented on students/donghun/users/views.py
> +                if check_password == True:
간단하게 `if check_password:` 이렇게도 처리할 수 있을 거 같습니다!

2022-01-20 00:58 UTC, lordmyshepherd requested changes

2022-01-20 00:58 UTC, lordmyshepherd commented on students/donghun/users/views.py
> +            if User.objects.filter(email = user_email).exists():
지금 로직을 보면 if문 안에 if를 사용하고 있습니다. if문을 많이 사용하면 로직이 분기가 되기 때문에 나중에 디버깅하기가 어려워집니다.
nested if문은 더욱 그렇겠죠?
```python
if User.objects.filter(email = user_email).exists():
    password_bcrypt = User.objects.get(email=user_email)
    check_password  = bcrypt.checkpw(user_data['password'].encode('utf-8'), password_bcrypt.password.encode('utf-8'))

    if check_password :
        access_token = jwt.encode({"user_id" : password_bcrypt.id}, SECRET_KEY, ALGORITHM)
        return JsonResponse({"access_token" : access_token}, status=200)
    else:
        return JsonResponse({"messeage" : "INVALID_USER"}, status=401)

else:
    return JsonResponse({"messeage" : "INVALID_USER"}, status=401)
```

그래서 최대한 nested if문은 사용하지 않아도 되는 경우에 피하는게 좋습니다.
```python
if not User.objects.filter(email = user_email).exists():
    return JsonResponse({"messeage" : "INVALID_USER"}, status=401)
    
user = User.objects.get(email=user_email)

if bcrypt.checkpw(user_data['password'].encode('utf-8'), user.password.encode('utf-8'))
    access_token = jwt.encode({"user_id" : password_bcrypt.id}, SECRET_KEY, ALGORITHM)
    return JsonResponse({"access_token" : access_token}, status=200)

return JsonResponse({"messeage" : "INVALID_USER"}, status=401)

```

2022-01-20 00:58 UTC, lordmyshepherd commented on students/donghun/users/views.py
> +                password_bcrypt = User.objects.get(email=user_email)
변수명을 잘 지어주셔야 합니다.
`User.objects.get(email=user_email)`가 실행되고 반환되는 데이터는 user 데이터인데 password_bcrypt라는 변수명을 붙여주고 있으니 코드를 읽는 사람 입장에서 혼란스럽습니다.

2022-01-20 04:40 UTC, DongKey777 commented on students/donghun/users/views.py
> +                password_bcrypt = User.objects.get(email=user_email)
피드백 확인 후 수정해서 다시 푸쉬했습니다  감사합니다 ! :)

2022-01-20 04:50 UTC, bigfanoftim requested changes

2022-01-20 04:50 UTC, bigfanoftim commented on students/donghun/users/views.py
> +from my_settings import SECRET_KEY,ALGORITHM
```python
# views.py

from my_settings import ALGORITHM, SECRET_KEY
```

`HS256`, `SECRET_KEY`와 같은 환경변수를 my_settings.py 파일로 관리하고 있습니다. my_settings.py 파일은 환경변수 관리로서의 역할만 하는 파일로서 [views.py](http://views.py) 또는 models.py에서 직접 import해서 사용하시면 views.py 파일이 my_settings.py 파일에 의존성이 생기게 됩니다.

만약에 환경변수 관리를 my_settings.py가 아니라 아래와 같이 다른 방법으로 관리하게 되면 views.py에 코드도 전부 수정해야되는 것이죠.

```python
# settings.py

DATABASES = {
    ..
    "PASSWORD" : os.environ.get("DB_PASSWORD")
}
```

그러므로 my_settings.py에서 환경변수를 import해서 사용하실 때에는 지금처럼 `from my_settings import ALGORITHM, SECRET_KEY` 방법이 아니라 `from django.conf import settings.ALGORITHM, settings.SECRET_KEY`를 사용해서 환경변수를 불러와서 사용해주세요.

2022-01-20 04:50 UTC, bigfanoftim commented on students/donghun/users/views.py
> +            user = User.objects.get(email=user_email)
```python
user = User.objects.get(email = email)

if not User.objects.filter(email=email).exists():
    return JsonResponse({"message": "INVALID_USER"}, status = 401)
```

`get` 메소드를 사용하여 조회했을 때 데이터베이스에 매칭되는 데이터가 없는 경우 python에서 error를 raise 합니다. 그렇기 때문에 `if not User.objects.filter(email=email).exists() :` 코드가 실행될 일이 없겠죠?

그러므로 위 if문 코드는 불필요한 코드입니다. `user = User.objects.get(email = email)` 에서 에러가 발생했을 경우에 except문에서 에러를 잡아줄 수 있도록 수정해주세요.

2022-01-20 07:43 UTC, bigfanoftim approved these changes
LGTM 👍

2022-01-20 07:43 UTC, merged