[동훈] Misson 2 : 모델링
wecode-bootcamp-korea/29-westagram-backend-3-team pull request #6
Opened 2022-01-14 07:13 UTC by DongKey777

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- user 앱 생성 , models.py 작성
		
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-14 07:22 UTC, bigfanoftim requested changes

2022-01-14 07:22 UTC, bigfanoftim commented on students/donghun/users/models.py
> +    contact = models.IntegerField(max_length=20, unique=True)
가독성을 위해 `=` 혹은 `:`를 기준으로 정렬해주세요!

```python
name     = models.CharField(...)
email    = models.CharField(...)
password = models.CharField(...)
```

2022-01-14 07:22 UTC, bigfanoftim commented on students/donghun/users/models.py
> +        db_table = "user"
class 명은 단수를 데이터베이스에 생성되는 테이블 명은 복수로 만드는 것이 컨벤션 입니다.

```python
class Meta:
    db_table = 'users'
```

2022-01-16 03:32 UTC, DongKey777 commented on students/donghun/users/models.py
> +    contact = models.IntegerField(max_length=20, unique=True)
확인 후 수정했습니다 !

2022-01-16 03:33 UTC, DongKey777 commented on students/donghun/users/models.py
> +        db_table = "user"
수정 후 푸쉬했습니다 !

2022-01-17 01:51 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-01-17 01:51 UTC, merged