[ 이강일 ] Mission : 3 회원가입 기능 구현
wecode-bootcamp-korea/29-westagram-backend-3-team pull request #7
Opened 2022-01-14 07:51 UTC by kangil2

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 및 회원정보 post, get 기능 구현했습니다.
- 한국 시간대로 설정 변경했습니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-14 08:08 UTC, bigfanoftim requested changes

2022-01-14 08:08 UTC, bigfanoftim commented on students/kangil/westagram/users/views.py
> +
```suggestion
```

2022-01-14 08:08 UTC, bigfanoftim commented on students/kangil/westagram/users/views.py
> +                return JsonResponse({'Message' : 'Invalid Email'}, status = 404)
`404`가 맞는지 다시 한 번 확인해주세요! 
`urls.py`에 정의되지 않은 주소로 요청을 한 번 보내시면 바로 알 수 있답니다~

2022-01-14 08:08 UTC, bigfanoftim commented on students/kangil/westagram/users/views.py
> +            user_info = User.objects.create(
`create` 후 반환되는 인스턴스를 변수 지정한 후 활용하지 않는 것으로 보이는데 굳이 변수에 담아준 이유가 있을까요?

2022-01-14 08:08 UTC, bigfanoftim commented on students/kangil/westagram/users/views.py
> +        return JsonResponse({'users' : user_list}, status = 200)
하나의 PR(브랜치)에는 하나의 기능만 담아주세요. 현재 PR은 회원가입 PR이므로 관련 없는 코드들은 전부 다 지워주세요~

2022-01-17 01:53 UTC, lordmyshepherd requested changes

2022-01-17 01:53 UTC, lordmyshepherd commented on students/kangil/westagram/users/views.py
> +                return JsonResponse({'Message': 'KEY_ERROR'}, status = 400)
이미 정규식으로 검증할 수 있는 경우 아닌가요?
2줄의 코드가 꼭 필요한지 궁금합니다!

2022-01-17 03:31 UTC, kangil2 commented on students/kangil/westagram/users/views.py
> +                return JsonResponse({'Message': 'KEY_ERROR'}, status = 400)
이메일이나 패스워드가 전달되지 않을 경우, {"message": "KEY_ERROR"}, status code 400 을 반환합니다.
라는 기능 정의를 보고 조건문을 사용해서 반환했는데 해당 조건문을 지웠을 때에는 해당 에러 메세지가 반환이 되지않아서 사용했었습니다

2022-01-17 05:26 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-01-17 05:26 UTC, merged

2022-01-17 05:26 UTC, bigfanoftim requested changes

2022-01-17 05:26 UTC, bigfanoftim commented on students/kangil/westagram/users/views.py
> +            PASSWORD_VALIDATION = re.compile(r'^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$')
정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.

```python
import re

from django.core.exceptions import ValidationError

REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

def validate_email(value) :    
    if not re.match(REGEX_EMAIL, value):
        raise ValidationError('INVALID_EMAIL_ADDRESS')

def validate_password(value) :
    if not re.match(REGEX_EMAIL, value):
        raise ValidationError('INVALID_PASSWORD')
```

2022-01-17 05:26 UTC, bigfanoftim commented on students/kangil/westagram/users/views.py
> +            return JsonResponse({'Message': 'FAILED'}, status = 400)
에러메세지를 정확하게 리턴해주세요!
```suggestion
            return JsonResponse({'Message': 'KEY_ERROR'}, status = 400)
```